const translations = {
    // ============================================================
    // 🇹🇭 ภาษาไทย
    // ============================================================
    "th": {
        "lang_name": "ภาษาไทย",
        
        // --- Titles ---
        "title_login": "เข้าสู่ระบบ - Consumer",
        "title_home": "หน้าแรก - Consumer",
        "title_order": "บันทึกออเดอร์",
        "title_task": "โถงภารกิจ",
        "title_service": "ศูนย์บริการ",
        "title_profile": "โปรไฟล์ของฉัน",

        // --- Login ---
        "login_header": "เข้าสู่ระบบ",
        "mobile_label": "เบอร์โทรศัพท์*",
        "password_label": "รหัสผ่าน*",
        "ph_mobile": "ระบุเบอร์โทรศัพท์",
        "ph_pass": "กรอกรหัสผ่าน",
        "login_btn": "เข้าสู่ระบบ",
        "register_btn": "ไปที่ลงทะเบียน",

        // --- Alerts & Popups ---
        "alert_success": "สำเร็จ",
        "alert_welcome": "ยินดีต้อนรับ",
        "alert_error": "ผิดพลาด",
        "alert_login_fail": "เบอร์โทรศัพท์ หรือ รหัสผ่าน ไม่ถูกต้อง",
        "alert_fill_info": "กรุณากรอกข้อมูลให้ครบถ้วน",
        "alert_connecting": "ระบบกำลังเชื่อมต่อ... กรุณารอสักครู่",
        "invite_code_title": "รหัสแนะนำเพื่อน",
        "invite_code_msg": "รหัสแนะนำของคุณคือ:",
        "confirm_logout": "คุณต้องการออกจากระบบหรือไม่?",

        // --- Notifications (แจ้งเตือน) ---
        "notif_header": "การแจ้งเตือน",
        "notif_close": "ปิด",
        "notif_empty": "ไม่มีการแจ้งเตือน",
        "n_wd_wait": "แจ้งถอนเงิน",
        "n_wd_ok": "ถอนเงินสำเร็จ",
        "n_wd_fail": "ถอนเงินถูกปฏิเสธ",
        "n_rc_wait": "แจ้งเติมเงิน",
        "n_rc_ok": "เติมเงินสำเร็จ",
        "n_rc_fail": "เติมเงินล้มเหลว",
        "n_msg_wait": "กำลังรอการตรวจสอบ",
        "n_msg_ok_wd": "อนุมัติแล้ว เงินเข้าบัญชี",
        "n_msg_ok_rc": "เข้ากระเป๋าแล้ว",
        "n_msg_fail": "ไม่ผ่านการอนุมัติ/ถูกยกเลิก",
        "n_amt": "ยอด",

        // --- Nav & Menu ---
        "nav_home": "หน้าแรก",
        "nav_order": "ออเดอร์",
        "nav_task": "ภารกิจ",
        "nav_service": "บริการ",
        "nav_my": "ฉัน",

        // --- Home ---
        "daily_tasks": "ภารกิจรายวัน",
        "urgent_tasks": "ค่าคอมมิชชั่นสูงสำหรับภารกิจด่วน",
        "loading_products": "กำลังโหลดสินค้า...",
        "no_products": "ไม่มีสินค้า",
        "start_work": "เริ่มจับออเดอร์",
        "mem_benefits": "สิทธิประโยชน์สมาชิก",
        "mem_desc": "ระดับสมาชิกที่สูงขึ้น รับภารกิจได้มากขึ้น<br>เพื่อเพลิดเพลินกับรายได้ที่มากขึ้น",
        "upgrade_now": "อัปเกรดทันที",
        "partners": "แบรนด์พันธมิตร",
        "partners_desc": "พันธมิตรทางธุรกิจของเรา",
        "service_center": "ศูนย์บริการ",
        "service_desc": "หากมีข้อสงสัยเพิ่มเติม โปรดติดต่อศูนย์บริการลูกค้าของเรา",
        "invite": "เชิญเพื่อน",
        "comp_qual": "เกี่ยวกับเรา",
        
        // --- Profile ---
        "balance": "ยอดเงินคงเหลือ",
        "credit_score": "เครดิต",
        "recharge": "เติมเงิน",
        "withdraw": "ถอนเงิน",
        "news": "ข่าวสาร",
        "menu_invite": "เชิญเพื่อน",
        "menu_order_record": "บันทึกออเดอร์",
        "menu_acc_details": "รายละเอียดบัญชี",
        "menu_fund_pwd": "รหัสผ่านถอนเงิน",
        "menu_bank_card": "บัญชีธนาคาร",
        "menu_logout": "ออกจากระบบ",
        "tab_all": "ทั้งหมด",
    "tab_pending": "รอการยื่น",
    "tab_completed": "เสร็จสิ้น",
    "tab_frozen": "ถูกระงับ",
    "txt_comm": "ค่าคอม",
    "btn_submit_order": "ยืนยันออเดอร์",
    "txt_no_data": "ไม่มีรายการ",
    "txt_order_id": "รหัสออเดอร์",
    "txt_order_time": "เวลา",

    // --- Order Matching Process & Modal ---
    "work_checking": "กำลังตรวจสอบสถานะ...",
    "work_loading_products": "กำลังโหลดสินค้า...",
    "work_matching": "กำลังจับคู่ออเดอร์...",
    "modal_matched_title": "จับคู่ออเดอร์สำเร็จ!",
    "modal_total_order": "ราคารวม",
    "modal_commission": "ค่าคอมมิชชั่น",
    "modal_return": "ยอดได้รับคืน",
    "modal_rating": "ให้คะแนน",
    "modal_review_label": "รีวิวสินค้า",
    "btn_submit_now": "ส่งออเดอร์ทันที",
    "alert_submit_success": "ส่งงานสำเร็จ!",
    "alert_submit_msg": "สำเร็จ",

    // --- News (ข่าวสาร) ---
    "news_header": "ข่าวสาร",
    "news_p1": "เนื่องในโอกาสฉลองครบรอบ 24 ปี CONSUMER PARTNER ได้เปิดตัวกิจกรรมดังต่อไปนี้เพื่อขอบคุณผู้ใช้ใหม่และผู้ใช้เก่าที่ให้การสนับสนุน CONSUMER PARTNER ของเราเป็นอย่างดี",
    "news_p2": "กิจกรรมมีดั่งนี้ :",
    "news_topup": "เติมเงิน",
    "news_bonus": "รับโบนัส",
    "news_p3": "หรือรางวัลมากกว่านี้สามารถติดต่อฝ่ายบริการลูกค้าร่วงหน้าเพื่อสอบถามเพิ่มเติม!",
    "news_footer": "พวกเราทีมงาน CONSUMER PARTNER ขออวยพรให้ทุกท่านมีความสุข！",
    "news_loading_done": "โหลดเสร็จสมบูรณ์",
    
    // --- Review Options (คำรีวิว) ---
    "rev_opt_1": "คุณภาพสินค้าดีเยี่ยม ตรงปกมาก",
    "rev_opt_2": "พอใจมาก จะกลับมาสั่งอีกแน่นอน",
    "rev_opt_3": "ราคาคุ้มค่ามาก ประทับใจ",
    "rev_opt_4": "ประสบการณ์การช้อปปิ้งที่ดีมาก",
    "rev_opt_5": "จัดส่งรวดเร็ว บริการดีเยี่ยม",
    // --- Work Page (Task Hall) ---
    "work_title": "โถงภารกิจ",
    "work_commission_rate": "อัตราค่าคอมมิชชั่น:",
    "work_today_comm": "ค่าคอมมิชชั่นทั้งหมด",
    "work_frozen": "ยอดเงินที่ถูกแช่แข็ง",
    "work_completed": "ออเดอร์ที่เสร็จสิ้น",
    "work_balance": "ยอดเงินคงเหลือ",
    "work_start_btn": "เริ่มจับออเดอร์",
    // --- Rules & Warning (ข้อความใหม่ตามรูป) ---
    "work_desc_title": "คำอธิบาย",
    "work_desc_1": "1.ระบบอิงตามเทคโนโลยี LBS และจับคู่สินค้าอัตโนมัติผ่านคลาวด์",
    "work_desc_2": "2.คุณไม่สามารถยกเลิกภารกิจได้ คุณต้องทำภารกิจที่ยังไม่ได้ทำให้เสร็จก่อน จึงจะสามารถรับภารกิจใหม่ได้",
    "work_warn_title": "คำเตือน",
    "work_warn_text": "เมื่อแพลตฟอร์มจับคู่คำสั่งซื้อให้กับผู้ใช้ ระบบจะส่งข้อมูลคำสั่งซื้อไปยังหลังบ้านของผู้ขาย หากผู้ใช้ไม่ได้ส่งคำสั่งซื้อภายใน 30 นาที จะมีการแช่แข็งจำนวนเงินของคำสั่งซื้อโดยระบบ เพื่อหลีกเลี่ยงระบบกำกับดูแล ระบบจะให้คะแนนบัญชีผู้ใช้ ซึ่งจะส่งผลต่อเวลาการจับคู่ครั้งต่อไปและชื่อเสียงของผู้ใช้! กรุณาคลิกหยุดสั่งซื้อทันทีเพื่อหลีกเลี่ยงการแช่แข็งเนื่องจากเกินเวลา",
        
// --- Service Page ---
    "service_title": "ศูนย์บริการ",
    "service_banner_title": "ต้องการความช่วยเหลือ?",
    "service_banner_desc": "ติดต่อฝ่ายบริการลูกค้าได้ตลอด 24 ชั่วโมง",
    "service_line_main": "ติดต่อฝ่ายบริการ",
    "service_line_backup": "Line Official (สำรอง)",
    "service_line_desc": "ติดต่อผ่านไลน์",
    "service_faq_title": "คำถามที่พบบ่อย (FAQ)",
    "faq_q1": "ถอนเงินนานไหม?",
    "faq_a1": "ปกติระบบจะดำเนินการภายใน 15-30 นาที",
    "faq_q2": "เติมเงินไม่เข้า?",
    "faq_a2": "กรุณาส่งสลิปให้แอดมินทาง Line หรือ Telegram",
    "faq_q3": "เวลาทำการ?",
    "faq_a3": "เราให้บริการตลอด 24 ชั่วโมง",
    
    // --- Contact Modal ---
    "modal_contact_title": "ติดต่อเจ้าหน้าที่",
    "modal_line_id": "Line ID:",
    "btn_copy": "คัดลอก",
    "alert_copied": "คัดลอกเรียบร้อยแล้ว",

    // --- Deposit & Password ---
    "modal_verify_title": "ยืนยันตัวตน",
    "modal_verify_desc": "กรุณากรอกรหัสผ่านเพื่อดำเนินการต่อ",
    "ph_verify_pwd": "รหัสผ่านของคุณ",
    "btn_confirm": "ยืนยัน",
    "alert_wrong_pwd_title": "รหัสผิด",
    "alert_wrong_pwd_msg": "รหัสผ่านไม่ถูกต้อง",
    
    "modal_amount_title": "ระบุยอดเงิน",
    "txt_min_amount": "ขั้นต่ำ:",
    "txt_pay_negative": "ชำระยอดติดลบ",
    "btn_deposit_submit": "แจ้งเติมเงิน",
    "alert_invalid_amount": "กรุณาระบุจำนวนเงินให้ถูกต้อง",
    "alert_amount_title": "ยอดเงินไม่ถูกต้อง",
    "alert_need_min": "ต้องเติมขั้นต่ำ",
    "alert_sending": "กำลังส่งข้อมูล...",
    
    "modal_dep_success_title": "แจ้งเติมเงินสำเร็จ",
    "modal_dep_success_msg": "รายการของคุณถูกส่งแล้ว<br>กรุณาติดต่อ Admin เพื่อยืนยันยอดเงิน",
    "btn_contact_admin": "ติดต่อ Admin",
    "btn_close_window": "ปิดหน้าต่าง",

    // --- Withdrawal ---
    "modal_wd_title_1": "ข้อมูลบัญชีรับเงิน",
    "lbl_bank": "ธนาคาร",
    "ph_bank": "ชื่อธนาคาร",
    "lbl_acc_name": "ชื่อบัญชี",
    "ph_acc_name": "ชื่อ-นามสกุล",
    "lbl_acc_no": "เลขที่บัญชี",
    "ph_acc_no": "ไม่ต้องมีขีด",
    "btn_next": "ถัดไป",
    
    "modal_wd_title_2": "รายละเอียดการถอน",
    "lbl_net_balance": "ยอดเงินสุทธิ (Net):",
    "lbl_frozen": "ถูกแช่แข็ง (Frozen):",
    "lbl_actual_withdraw": "ถอนได้จริง:",
    "lbl_fee": "ค่าธรรมเนียม",
    "lbl_receive_amount": "ยอดเงินที่จะได้รับ:",
    "ph_wd_pwd": "รหัสผ่านยืนยัน",
    "btn_confirm_wd": "ยืนยันการถอน",
    
    "alert_wd_success_title": "ดำเนินการแล้ว",
    "alert_wd_success_msg": "รายการถอนของคุณถูกส่งแล้ว<br>กรุณาติดต่อ Admin เพื่ออนุมัติยอดเงิน",

    // --- Pending Order Warning ---
        "warn_pending_title": "ออเดอร์ค้าง!",
        "warn_pending_msg": "คุณมีออเดอร์ที่ยังไม่เสร็จสิ้น!<br>กรุณาทำรายการให้เสร็จก่อน",
        "btn_go_order": "ไปทำรายการ",

    "reg_header": "ลงทะเบียนบัญชี",
    "reg_mobile": "หมายเลขโทรศัพท์*",
    "reg_ph_mobile": "กรุณากรอกหมายเลขโทรศัพท์",
    "reg_pass": "รหัสผ่านเข้าสู่ระบบ*",
    "reg_ph_pass": "กรุณากรอกรหัสผ่าน",
    "reg_confirm_pass": "ยืนยันรหัสผ่าน*",
    "reg_ph_confirm_pass": "กรุณายืนยันรหัสผ่าน",
    "reg_invite": "รหัสการเชิญ*",
    "reg_ph_invite": "กรุณาใส่รหัสเชิญ",
    "reg_agree": "ฉันได้ตกลงในข้อตกลงการให้บริการ",
    "reg_btn_submit": "สมัครเลย",
    "alert_reg_success": "สมัครสมาชิกสำเร็จ",
    "alert_reg_fail": "การสมัครล้มเหลว",
    "alert_pass_mismatch": "รหัสผ่านไม่ตรงกัน",
    "alert_invite_invalid": "รหัสเชิญไม่ถูกต้อง (ไม่พบในระบบ)",
    "alert_user_exists": "เบอร์โทรศัพท์นี้ถูกใช้งานแล้ว",
    "alert_term_agree": "กรุณายอมรับเงื่อนไขการให้บริการ",
    
    "alert_incomplete_info": "ข้อมูลไม่ครบ",
    "alert_fill_bank": "กรุณากรอกข้อมูลบัญชีให้ครบถ้วน",
    "alert_checking_limit": "กำลังตรวจสอบวงเงิน...",
    "alert_quota_exceeded": "โควต้าเต็ม",
    "alert_quota_msg": "คุณใช้โควต้าการถอนเกินกำหนดแล้ว",
    "alert_wd_min": "ยอดเงินต่ำเกินไป",
    "alert_wd_min_msg": "ระบบกำหนดให้ถอนขั้นต่ำ:",
    "alert_wd_bal_low": "ยอดเงินไม่พอ",
    "alert_wd_frozen_msg": "ยอดเงินที่ถอนได้ไม่เพียงพอ (อาจติด Frozen)",

    "cancel": "ยกเลิก",

        // --- เพิ่มใหม่: ระบบแจ้งเตือนและธนาคาร ---
        "alert_account_blocked": "บัญชีของคุณถูกระงับการทำภารกิจชั่วคราว กรุณาติดต่อฝ่ายบริการลูกค้า",
        
        "bank_title": "ข้อมูลธนาคาร",
        "bank_grp_main": "ข้อมูลหลัก",
        "bank_grp_detail": "รายละเอียดเพิ่มเติม",
        "bank_grp_wallet": "บัญชีดิจิทัล / วอลเล็ท",
        
        "bank_lbl_holder": "ชื่อเจ้าของบัญชี",
        "bank_ph_holder": "ชื่อ-นามสกุลจริง",
        "bank_lbl_name": "ชื่อธนาคาร",
        "bank_ph_name": "เช่น กสิกรไทย, ไทยพาณิชย์",
        "bank_lbl_acc": "เลขบัญชี",
        "bank_ph_acc": "เลขบัญชี (ไม่ต้องมีขีด)",
        
        "bank_lbl_code": "รหัสธนาคาร",
        "bank_ph_code": "Bank Code",
        "bank_lbl_branch": "รหัสสาขา",
        "bank_ph_branch": "Branch Code",
        "bank_lbl_phone": "เบอร์โทรที่ผูกบัญชี",
        "bank_ph_phone": "เบอร์โทรศัพท์",
        "bank_lbl_addr": "ที่อยู่เปิดบัญชี",
        "bank_ph_addr": "สาขา หรือ ที่อยู่",
        "bank_lbl_ifsc": "IFSC / CPF",
        "bank_ph_ifsc": "รหัส IFSC/CPF",
        
        "bank_lbl_digital": "บัญชีดิจิทัล",
        "bank_ph_digital": "Digital Account",
        "bank_lbl_w_no": "เบอร์วอลเล็ท",
        "bank_ph_w_no": "Wallet Number",
        "bank_lbl_w_acc": "ชื่อบัญชีวอลเล็ท",
        "bank_ph_w_acc": "Wallet Account Name",
        
        "btn_save_data": "บันทึกข้อมูล",
        "btn_cancel": "ยกเลิก",
        "modal_confirm_save": "ยืนยันการบันทึก?",
        "modal_confirm_msg": "คุณต้องการอัปเดตข้อมูลบัญชีใช่หรือไม่?",
        "alert_save_success": "บันทึกข้อมูลเรียบร้อยแล้ว",
        // --- Common ---
        "lang_select": "เลือกภาษา",
        "confirm": "ตกลง"
        
        
    },

    // ============================================================
    // 🇬🇧 English
    // ============================================================
    "en": {
        "lang_name": "English",
        "title_login": "Login - Consumer",
        "title_home": "Homepage - Consumer",
        "title_order": "Order Records",
        "title_task": "Task Hall",
        "title_service": "Service Center",
        "title_profile": "My Profile",

        "login_header": "Login",
        "mobile_label": "Mobile number*",
        "password_label": "Login password*",
        "ph_mobile": "Enter mobile number",
        "ph_pass": "Enter password",
        "login_btn": "Login",
        "register_btn": "To Register",

        // ... (ในหมวดภาษาอังกฤษ "en")
    "news_header": "News",
    "news_p1": "To celebrate the 24th Anniversary of CONSUMER PARTNER, we are launching the following activities to thank both new and loyal users for their continuous support.",
    "news_p2": "Activity Details:",
    "news_topup": "Deposit",
    "news_bonus": "Get Bonus",
    "news_p3": "For more rewards, please contact customer service in advance for details!",
    "news_footer": "The CONSUMER PARTNER team wishes everyone happiness!",
    "news_loading_done": "Loading complete",

        // ... (ภาษาอังกฤษ "en")
    "work_checking": "Checking Pending...",
    "work_loading_products": "Loading Products...",
    "work_matching": "Matching Order...",
    "modal_matched_title": "Order Matched!",
    "modal_total_order": "Total Order",
    "modal_commission": "Commission",
    "modal_return": "Return Amount",
    "modal_rating": "Order Rating",
    "modal_review_label": "Order Review",
    "btn_submit_now": "Submit Order Now",
    "alert_submit_success": "Submission Success!",
    "alert_submit_msg": "Commission added to account",

    "rev_opt_1": "The product quality is excellent and exactly matches description.",
    "rev_opt_2": "I am very satisfied and will purchase again.",
    "rev_opt_3": "Very pleased with the reasonable price.",
    "rev_opt_4": "This shopping experience is highly satisfactory.",
    "rev_opt_5": "Fast delivery and good service.",

        "alert_success": "Success",
        "alert_welcome": "Welcome",
        "alert_error": "Note",
        "alert_login_fail": "Incorrect mobile number or password",
        "alert_fill_info": "Please fill in all information",
        "alert_connecting": "Connecting... Please wait",
        "invite_code_title": "Invite Code",
        "invite_code_msg": "Your invite code is:",
        "confirm_logout": "Are you sure you want to logout?",

        "service_title": "Customer Service",
    "service_banner_title": "Need Help?",
    "service_banner_desc": "Contact customer support 24/7",
    "service_line_main": "Admin Contack",
    "service_line_backup": "Line Official (Backup)",
    "service_line_desc": "Contact via Line",
    "service_faq_title": "FAQ",
    "faq_q1": "How long does withdrawal take?",
    "faq_a1": "Usually processed within 15-30 minutes",
    "faq_q2": "Recharge not received?",
    "faq_a2": "Please send the slip to Admin via Line or Telegram",
    "faq_q3": "Working hours?",
    "faq_a3": "We are available 24 hours",
    "modal_contact_title": "Contact Support",
    "modal_line_id": "Line ID:",
    "btn_copy": "Copy",
    "alert_copied": "Copied to clipboard",

    // ... (ในหมวดภาษาอังกฤษ "en")
    "modal_verify_title": "Verify Identity",
    "modal_verify_desc": "Please enter password to continue",
    "ph_verify_pwd": "Your password",
    "btn_confirm": "Confirm",
    "alert_wrong_pwd_title": "Wrong Password",
    "alert_wrong_pwd_msg": "Incorrect password",
    
    "modal_amount_title": "Enter Amount",
    "txt_min_amount": "Minimum:",
    "txt_pay_negative": "Pay Negative Balance",
    "btn_deposit_submit": "Submit Recharge",
    "alert_invalid_amount": "Please enter valid amount",
    "alert_amount_title": "Invalid Amount",
    "alert_need_min": "Minimum required",
    "alert_sending": "Sending...",
    
    "modal_dep_success_title": "Recharge Successful",
    "modal_dep_success_msg": "Your request has been sent.<br>Please contact Admin to verify.",
    "btn_contact_admin": "Contact Admin",
    "btn_close_window": "Close Window",

    "modal_wd_title_1": "Bank Account Info",
    "lbl_bank": "Bank Name",
    "ph_bank": "Bank Name",
    "lbl_acc_name": "Account Name",
    "ph_acc_name": "Full Name",
    "lbl_acc_no": "Account Number",
    "ph_acc_no": "No dashes",
    "btn_next": "Next",
    
    "modal_wd_title_2": "Withdrawal Details",
    "lbl_net_balance": "Net Balance:",
    "lbl_frozen": "Frozen:",
    "lbl_actual_withdraw": "Available:",
    "lbl_fee": "Fee",
    "lbl_receive_amount": "Net Receive:",
    "ph_wd_pwd": "Confirm Password",
    "btn_confirm_wd": "Confirm Withdrawal",
    
    "alert_wd_success_title": "Processed",
    "alert_wd_success_msg": "Withdrawal request sent.<br>Please contact Admin for approval.",
    
    "alert_incomplete_info": "Incomplete Info",
    "alert_fill_bank": "Please fill in all bank details",
    "alert_checking_limit": "Checking Limit...",
    "alert_quota_exceeded": "Quota Exceeded",
    "alert_quota_msg": "You have reached the withdrawal limit.",
    "alert_wd_min": "Amount too low",
    "alert_wd_min_msg": "Minimum withdrawal amount:",
    "alert_wd_bal_low": "Insufficient Balance",
    "alert_wd_frozen_msg": "Available balance insufficient (Frozen)",

    // ... (ในหมวดภาษาอังกฤษ "en")
    "reg_header": "Register Account",
    "reg_mobile": "Mobile Number*",
    "reg_ph_mobile": "Enter mobile number",
    "reg_pass": "Password*",
    "reg_ph_pass": "Enter password",
    "reg_confirm_pass": "Confirm Password*",
    "reg_ph_confirm_pass": "Confirm your password",
    "reg_invite": "Invitation Code*",
    "reg_ph_invite": "Enter invitation code",
    "reg_agree": "I agree to the Terms of Service",
    "reg_btn_submit": "Register Now",
    "alert_reg_success": "Registration Successful",
    "alert_reg_fail": "Registration Failed",
    "alert_pass_mismatch": "Passwords do not match",
    "alert_invite_invalid": "Invalid Invitation Code",
    "alert_user_exists": "Phone number already exists",
    "alert_term_agree": "Please agree to the Terms of Service",

        // --- Order Page (เพิ่มใหม่) ---
    // ... (ในหมวดภาษาอังกฤษ "en")
    "tab_all": "All",
    "tab_pending": "Pending",
    "tab_completed": "Completed",
    "tab_frozen": "Frozen",
    "txt_comm": "Commission",
    "btn_submit_order": "Submit Order",
    "txt_no_data": "No Data",
    "txt_order_id": "Order ID",
    "txt_order_time": "Time",

    "work_title": "Task Hall",
    "work_commission_rate": "Commission Rate:",
    "work_today_comm": "Today's Commission",
    "work_frozen": "Frozen Amount",
    "work_completed": "Orders Completed",
    "work_balance": "Account Balance",
    "work_start_btn": "Start Grabbing Orders",
    // --- Pending Order Warning ---
        "warn_pending_title": "Pending Order!",
        "warn_pending_msg": "You have unfinished orders!<br>Please complete them first.",
        "btn_go_order": "Go to Order",

   "work_desc_title": "Description",
    "work_desc_1": "1. The system uses LBS technology to auto-match products via cloud.",
    "work_desc_2": "2. You cannot cancel tasks. You must complete pending tasks before receiving new ones.",
    "work_warn_title": "Warning",
    "work_warn_text": "When matched, order data is sent to the seller. If not submitted within 30 mins, the amount will be frozen to comply with regulations. The system scores your account, affecting future matching and reputation! Please click stop ordering immediately to avoid timeout freezing.",
        // --- Notifications ---
        "notif_header": "Notifications",
        "notif_close": "Close",
        "notif_empty": "No notifications",
        "n_wd_wait": "Withdraw Request",
        "n_wd_ok": "Withdraw Success",
        "n_wd_fail": "Withdraw Failed",
        "n_rc_wait": "Recharge Request",
        "n_rc_ok": "Recharge Success",
        "n_rc_fail": "Recharge Failed",
        "n_msg_wait": "Waiting for review",
        "n_msg_ok_wd": "Approved, money sent to account",
        "n_msg_ok_rc": "Added to wallet",
        "n_msg_fail": "Rejected / Cancelled",
        "n_amt": "Amount",

        "nav_home": "Homepage",
        "nav_order": "Order",
        "nav_task": "Task",
        "nav_service": "Service",
        "nav_my": "My",

        "daily_tasks": "Daily Tasks",
        "urgent_tasks": "Higher Commission for Urgent Tasks",
        "loading_products": "Loading products...",
        "no_products": "No products",
        "start_work": "Start Grabbing Orders",
        "mem_benefits": "Membership Benefits",
        "mem_desc": "HIGHER MEMBERSHIP LEVELS, TAKING<br>ON MORE TASKS TO ENJOY MORE EARNINGS.",
        "upgrade_now": "Upgrade Now",
        "partners": "Partner Brands",
        "partners_desc": "Brand Partners",
        "service_center": "Service Center",
        "service_desc": "For further inquiries, please contact our Customer Service Center",
        "invite": "Invite Friends",
        "comp_qual": "About Us",

        "balance": "Account Balance",
        "credit_score": "Credit Score",
        "recharge": "Recharge",
        "withdraw": "Withdraw",
        "news": "News",
        "menu_invite": "Invite Friends",
        "menu_order_record": "Order Record",
        "menu_acc_details": "Account Details",
        "menu_fund_pwd": "Fund Password",
        "menu_bank_card": "Bank Card",
        "menu_logout": "Logout",

        "lang_select": "Select Language",
        "confirm": "Confirm",
        "cancel": "Cancel",

        // --- New: Alert & Bank Info ---
        "alert_account_blocked": "Your account is suspended. Please contact admin.",
        
        "bank_title": "Bank Info",
        "bank_grp_main": "Main Info",
        "bank_grp_detail": "Details",
        "bank_grp_wallet": "Digital / Wallet",
        
        "bank_lbl_holder": "Account Holder",
        "bank_ph_holder": "Full Name",
        "bank_lbl_name": "Bank Name",
        "bank_ph_name": "Bank Name",
        "bank_lbl_acc": "Account No.",
        "bank_ph_acc": "Account Number",
        
        "bank_lbl_code": "Bank Code",
        "bank_ph_code": "Bank Code",
        "bank_lbl_branch": "Branch Code",
        "bank_ph_branch": "Branch Code",
        "bank_lbl_phone": "Registered Phone",
        "bank_ph_phone": "Phone Number",
        "bank_lbl_addr": "Registered Address",
        "bank_ph_addr": "Address / Branch",
        "bank_lbl_ifsc": "IFSC / CPF",
        "bank_ph_ifsc": "IFSC/CPF Code",
        
        "bank_lbl_digital": "Digital Account",
        "bank_ph_digital": "Digital Account ID",
        "bank_lbl_w_no": "Wallet No.",
        "bank_ph_w_no": "Wallet Number",
        "bank_lbl_w_acc": "Wallet Name",
        "bank_ph_w_acc": "Wallet Account Name",
        
        "btn_save_data": "Save Data",
        "btn_cancel": "Cancel",
        "modal_confirm_save": "Confirm Save?",
        "modal_confirm_msg": "Do you want to update account info?",
        "alert_save_success": "Data saved successfully"
    

    },

    // ============================================================
    // 🇲🇲 Myanmar
    // ============================================================
    "mm": {
        "lang_name": "မြန်မာ",
        "title_login": "ဝင်ရောက်ရန် - Consumer",
        "title_home": "ပင်မစာမျက်နှာ - Consumer",
        "title_order": "အော်ဒါမှတ်တမ်း",
        "title_task": "အလုပ်ခန်းမ",
        "title_service": "ဝန်ဆောင်မှုစင်တာ",
        "title_profile": "ကျွန်ုပ်၏ ပရိုဖိုင်",
        "tab_all": "အားလုံး",
    "tab_pending": "ဆိုင်းငံ့",
    "tab_completed": "ပြီးစီး",
    "tab_frozen": "ထိန်းချုပ်",
    "txt_comm": "ကော်မရှင်",
    "btn_submit_order": "အော်ဒါတင်သွင်းမည်",
    "txt_no_data": "ဒေတာမရှိပါ",
    "txt_order_id": "အော်ဒါ ID",
    "txt_order_time": "အချိန်",
    "reg_header": "အကောင့်မှတ်ပုံတင်ရန်",
    "reg_mobile": "ဖုန်းနံပါတ်*",
    "reg_ph_mobile": "ကျေးဇူးပြု၍ ဖုန်းနံပါတ်ထည့်ပါ",
    "reg_pass": "စကားဝှက်*",
    "reg_ph_pass": "ကျေးဇူးပြု၍ စကားဝှက်ထည့်ပါ",
    "reg_confirm_pass": "စကားဝှက်အတည်ပြုပါ*",
    "reg_ph_confirm_pass": "ကျေးဇူးပြု၍ စကားဝှက်ကို ထပ်မံအတည်ပြုပါ",
    "reg_invite": "ဖိတ်ကြားမှုကုဒ်*",
    "reg_ph_invite": "ဖိတ်ကြားမှုကုဒ်ထည့်ပါ",
    "reg_agree": "ဝန်ဆောင်မှုစည်းမျဉ်းများကို သဘောတူပါသည်",
    "reg_btn_submit": "မှတ်ပုံတင်မည်",
    "alert_reg_success": "မှတ်ပုံတင်ခြင်း အောင်မြင်ပါသည်",
    "alert_reg_fail": "မှတ်ပုံတင်ခြင်း မအောင်မြင်ပါ",
    "alert_pass_mismatch": "စကားဝှက် မကိုက်ညီပါ",
    "alert_invite_invalid": "ဖိတ်ကြားမှုကုဒ် မမှန်ကန်ပါ (စနစ်တွင်မရှိပါ)",
    "alert_user_exists": "ဤဖုန်းနံပါတ်ကို အသုံးပြုထားပြီးဖြစ်သည်",
    "alert_term_agree": "ကျေးဇူးပြု၍ ဝန်ဆောင်မှုစည်းမျဉ်းများကို သဘောတူပါ",

    // --- Pending Order Warning ---
        "warn_pending_title": "အော်ဒါကျန်နေသည်!",
        "warn_pending_msg": "မပြီးပြတ်သေးသော အော်ဒါရှိနေသည်<br>ကျေးဇူးပြု၍ ပြီးအောင်လုပ်ပါ",
        "btn_go_order": "သွားရောက်စစ်ဆေးမည်",

    // ... (ภาษาพม่า "mm")
    "news_header": "သတင်း",
    "news_p1": "CONSUMER PARTNER ၏ ၂၄ နှစ်ပြည့် နှစ်ပတ်လည် အထိမ်းအမှတ်အနေဖြင့် အသုံးပြုသူများကို ကျေးဇူးတုံ့ပြန်ရန် အောက်ပါလှုပ်ရှားမှုများကို စတင်လိုက်ပါသည်။",
    "news_p2": "လှုပ်ရှားမှုများမှာ :",
    "news_topup": "ငွေဖြည့်",
    "news_bonus": "ဘောနပ်စ်ရယူ",
    "news_p3": "ဆုလက်ဆောင်များ ပိုမိုရရှိရန် ဝန်ဆောင်မှုဌာနသို့ ဆက်သွယ်မေးမြန်းနိုင်ပါသည်။",
    "news_footer": "CONSUMER PARTNER အဖွဲ့သားများမှ သင့်အား ပျော်ရွှင်ပါစေကြောင်း ဆုမွန်ကောင်း တောင်းလိုက်ပါသည်!",
    "news_loading_done": "ပြီးစီးပါပြီ",

    // ... (ในหมวด "mm" ให้เพิ่มต่อท้าย)
    "work_checking": "အခြေအနေ စစ်ဆေးနေသည်...",
    "work_loading_products": "ကုန်ပစ္စည်းများကို ဖွင့်နေပါသည်...",
    "work_matching": "အော်ဒါ တွဲဖက်နေသည်...",
    "modal_matched_title": "အော်ဒါ တွဲဖက်မှု အောင်မြင်သည်!",
    "modal_total_order": "စုစုပေါင်း အော်ဒါ",
    "modal_commission": "ကော်မရှင်",
    "modal_return": "ပြန်ရငွေ",
    "modal_rating": "အဆင့်သတ်မှတ်ချက်",
    "modal_review_label": "သုံးသပ်ချက်",
    "btn_submit_now": "အော်ဒါ ယခုတင်သွင်းမည်",
    "alert_submit_success": "တင်သွင်းမှု အောင်မြင်သည်!",
    "alert_submit_msg": "ကော်မရှင် ငွေစာရင်းသို့ ရောက်ရှိပါပြီ",

    // --- Review Options ---
    "rev_opt_1": "အရည်အသွေး အလွန်ကောင်းမွန်ပြီး ပုံစံတူပါသည်။",
    "rev_opt_2": "အလွန်ကျေနပ်ပြီး ထပ်မံဝယ်ယူပါမည်။",
    "rev_opt_3": "ဈေးနှုန်း သက်သာပြီး အလွန်သဘောကျပါသည်။",
    "rev_opt_4": "ဈေးဝယ်ရတာ အလွန်စိတ်ကျေနပ်မှု ရရှိပါသည်။",
    "rev_opt_5": "ပို့ဆောင်မှု မြန်ဆန်ပြီး ဝန်ဆောင်မှု ကောင်းမွန်ပါသည်။",

    // ... (ภาษาพม่า "mm")
    "modal_verify_title": "အတည်ပြုပါ",
    "modal_verify_desc": "ဆက်လက်လုပ်ဆောင်ရန် စကားဝှက်ထည့်ပါ",
    "ph_verify_pwd": "သင်၏ စကားဝှက်",
    "btn_confirm": "အတည်ပြု",
    "alert_wrong_pwd_title": "စကားဝှက်မှားနေသည်",
    "alert_wrong_pwd_msg": "စကားဝှက် မမှန်ကန်ပါ",
    "modal_amount_title": "ပမာဏထည့်ပါ",
    "txt_min_amount": "အနည်းဆုံး:",
    "txt_pay_negative": "အနှုတ်ပြငွေပေးချေခြင်း",
    "btn_deposit_submit": "ငွေဖြည့်မည်",
    "alert_invalid_amount": "မှန်ကန်သောပမာဏထည့်ပါ",
    "alert_amount_title": "ပမာဏ မမှန်ကန်ပါ",
    "alert_need_min": "အနည်းဆုံးလိုအပ်သည်",
    "alert_sending": "ပေးပို့နေသည်...",
    "modal_dep_success_title": "ငွေဖြည့်သွင်းမှု အောင်မြင်သည်",
    "modal_dep_success_msg": "ပေးပို့ပြီးပါပြီ<br>Admin ကို ဆက်သွယ်ပါ",
    "btn_contact_admin": "Admin ကိုဆက်သွယ်ရန်",
    "btn_close_window": "ပိတ်ပါ",

        "login_header": "ဝင်ရောက်ရန်",
        "mobile_label": "ဖုန်းနံပါတ်*",
        "password_label": "စကားဝှက်*",
        "ph_mobile": "ဖုန်းနံပါတ်ထည့်ပါ",
        "ph_pass": "စကားဝှက်ထည့်ပါ",
        "login_btn": "ဝင်ရောက်မည်",
        "register_btn": "အကောင့်ဖွင့်ရန်",

        "work_title": "အလုပ်ခန်းမ",
    "work_commission_rate": "ကော်မရှင်နှုန်းထား:",
    "work_today_comm": "ယနေ့ ကော်မရှင်",
    "work_frozen": "ထိန်းသိမ်းထားငွေ",
    "work_completed": "ပြီးစီးသော အော်ဒါများ",
    "work_balance": "လက်ကျန်ငွေ",
    "work_start_btn": "အော်ဒါစတင်ဖမ်းယူမည်",

 "work_desc_title": "ရှင်းလင်းချက်",
    "work_desc_1": "1. စနစ်သည် LBS နည်းပညာကို အသုံးပြုပြီး Cloud မှတဆင့် ကုန်ပစ္စည်းများကို အလိုအလျောက် တွဲဖက်ပေးသည်။",
    "work_desc_2": "2. လုပ်ငန်းများကို ပယ်ဖျက်၍မရပါ။ လုပ်လက်စများကို ပြီးစီးအောင်လုပ်မှသာ အသစ်လက်ခံနိုင်မည်။",
    "work_warn_title": "သတိပေးချက်",
    "work_warn_text": "အော်ဒါတွဲဖက်ပြီးပါက ရောင်းသူထံ ဒေတာပေးပို့သည်။ မိနစ် ၃၀ အတွင်း မတင်ပြပါက စည်းကမ်းထိန်းသိမ်းရေးအရ ငွေပမာဏကို ထိန်းချုပ်လိုက်မည်။ စနစ်က သင့်အကောင့်ကို အမှတ်ပေးမည်ဖြစ်ပြီး နောင်တွင် ထိခိုက်နိုင်သည်။ အချိန်လွန်၍ အကောင့်ပိတ်ခြင်းကို ရှောင်ရှားရန် အော်ဒါရပ်တန့်ခြင်းကို ချက်ချင်းနှိပ်ပါ။",
        "alert_success": "အောင်မြင်သည်",
        "alert_welcome": "ကြိုဆိုပါသည်",
        "alert_error": "မှားယွင်းနေသည်",
        "alert_login_fail": "ဖုန်းနံပါတ် သို့မဟုတ် စကားဝှက် မှားယွင်းနေသည်",
        "alert_fill_info": "ကျေးဇူးပြု၍ အချက်အလက်များ ပြည့်စုံစွာဖြည့်ပါ",
        "alert_connecting": "ချိတ်ဆက်နေသည်... ကျေးဇူးပြု၍ ခဏစောင့်ပါ",
        "invite_code_title": "ဖိတ်ခေါ်ကုဒ်",
        "invite_code_msg": "သင်၏ ဖိတ်ခေါ်ကုဒ်မှာ:",
        "confirm_logout": "အကောင့်မှ ထွက်လိုပါသလား?",

        // --- Withdrawal ---
    "modal_wd_title_1": "ငွေလက်ခံမည့်အကောင့် အချက်အလက်များ",
    "lbl_bank": "ဘဏ်",
    "ph_bank": "ဘဏ်",
    "lbl_acc_name": "အကောင့်အမည်",
    "ph_acc_name": "အမည်အပြည့်အစုံ",
    "lbl_acc_no": "အကောင့်နံပါတ်",
    "ph_acc_no": "ဒက်ရှ် (-) မထည့်ရ",
    "btn_next": "ရှေ့ဆက်",
    
    "modal_wd_title_2": "ငွေထုတ်ယူမှု အသေးစိတ်",
    "lbl_net_balance": "လက်ကျန်ငွေ (Net):",
    "lbl_frozen": "ထိန်းသိမ်းထားငွေ (Frozen):",
    "lbl_actual_withdraw": "ထုတ်ယူနိုင်သောငွေ:",
    "lbl_fee": "ဝန်ဆောင်ခ",
    "lbl_receive_amount": "ရရှိမည့်ပမာဏ:",
    "ph_wd_pwd": "အတည်ပြု စကားဝှက်",
    "btn_confirm_wd": "ငွေထုတ်ရန် အတည်ပြု",
    
    "alert_wd_success_title": "ဆောင်ရွက်ပြီး",
    "alert_wd_success_msg": "ငွေထုတ်ရန် တောင်းဆိုမှု ပေးပို့ပြီးပါပြီ<br>အတည်ပြုရန် Admin ကို ဆက်သွယ်ပါ",
    
    "alert_incomplete_info": "အချက်အလက် မပြည့်စုံပါ",
    "alert_fill_bank": "ဘဏ်အချက်အလက်များ ပြည့်စုံစွာ ဖြည့်ပါ",
    "alert_checking_limit": "ကန့်သတ်ချက် စစ်ဆေးနေသည်...",
    "alert_quota_exceeded": "ကန့်သတ်ချက် ပြည့်သွားပါပြီ",
    "alert_quota_msg": "ငွေထုတ်ယူနိုင်သည့် အကြိမ်ရေ ကုန်ဆုံးသွားပါပြီ",
    "alert_wd_min": "ပမာဏ နည်းလွန်းသည်",
    "alert_wd_min_msg": "အနည်းဆုံး ထုတ်ယူရမည့် ပမာဏ:",
    "alert_wd_bal_low": "လက်ကျန်ငွေ မလုံလောက်ပါ",
    "alert_wd_frozen_msg": "ထုတ်ယူနိုင်သောငွေ မလုံလောက်ပါ (Frozen ဖြစ်နေနိုင်သည်)",

        // --- Notifications ---
        "notif_header": "အသိပေးချက်များ",
        "notif_close": "ပိတ်ပါ",
        "notif_empty": "အသိပေးချက် မရှိပါ",
        "n_wd_wait": "ငွေထုတ်ရန် တောင်းဆိုမှု",
        "n_wd_ok": "ငွေထုတ်ယူမှု အောင်မြင်သည်",
        "n_wd_fail": "ငွေထုတ်ယူမှု မအောင်မြင်ပါ",
        "n_rc_wait": "ငွေဖြည့်ရန် တောင်းဆိုမှု",
        "n_rc_ok": "ငွေဖြည့်သွင်းမှု အောင်မြင်သည်",
        "n_rc_fail": "ငွေဖြည့်သွင်းမှု မအောင်မြင်ပါ",
        "n_msg_wait": "စစ်ဆေးနေဆဲ",
        "n_msg_ok_wd": "အတည်ပြုပြီး၊ ငွေလွှဲပြီးပါပြီ",
        "n_msg_ok_rc": "ပိုက်ဆံအိတ်ထဲသို့ ထည့်ပြီးပါပြီ",
        "n_msg_fail": "ပယ်ချလိုက်သည်",
        "n_amt": "ပမာဏ",

        "service_title": "ဝန်ဆောင်မှုစင်တာ",
    "service_banner_title": "အကူအညီလိုပါသလား?",
    "service_banner_desc": "ဖောက်သည်ဝန်ဆောင်မှုကို ၂၄ နာရီ ဆက်သွယ်နိုင်ပါသည်",
    "service_line_main": "Line Official (အဓိက)",
    "service_line_backup": "Line Official (မိတ္တူ)",
    "service_line_desc": "Line မှတဆင့် ဆက်သွယ်ပါ",
    "service_faq_title": "မေးလေ့ရှိသောမေးခွန်းများ (FAQ)",
    "faq_q1": "ငွေထုတ်ရန် ဘယ်လောက်ကြာမလဲ?",
    "faq_a1": "ပုံမှန်အားဖြင့် ၁၅-၃၀ မိနစ်အတွင်း ဆောင်ရွက်ပေးသည်",
    "faq_q2": "ငွေဖြည့်မဝင်ဘူးလား?",
    "faq_a2": "ကျေးဇူးပြု၍ စလစ်ကို Admin ထံ Line သို့မဟုတ် Telegram မှ ပေးပို့ပါ",
    "faq_q3": "အလုပ်ချိန်?",
    "faq_a3": "ကျွန်ုပ်တို့ ၂၄ နာရီ ဝန်ဆောင်မှုပေးပါသည်",
    
    // --- Contact Modal ---
    "modal_contact_title": "ဝန်ဆောင်မှုအဖွဲ့ကို ဆက်သွယ်ရန်",
    "modal_line_id": "Line ID:",
    "btn_copy": "ကူးယူမည်",
    "alert_copied": "ကူးယူပြီးပါပြီ",

        "nav_home": "ပင်မ",
        "nav_order": "အော်ဒါ",
        "nav_task": "အလုပ်",
        "nav_service": "ဝန်ဆောင်မှု",
        "nav_my": "ကျွန်ုပ်",

        "daily_tasks": "နေ့စဉ်လုပ်ငန်းဆောင်တာများ",
        "urgent_tasks": "အရေးပေါ်အလုပ်များအတွက် ကော်မရှင်ပိုများ",
        "loading_products": "ကုန်ပစ္စည်းများကို ဖွင့်နေပါသည်...",
        "no_products": "ကုန်ပစ္စည်းမရှိပါ",
        "start_work": "အော်ဒါစတင်ဖမ်းယူမည်",
        "mem_benefits": "အသင်းဝင် အကျိုးခံစားခွင့်များ",
        "mem_desc": "အသင်းဝင်အဆင့်မြင့်လေ အလုပ်များများလုပ်နိုင်ပြီး<br>ဝင်ငွေပိုမိုရရှိလေဖြစ်သည်။",
        "upgrade_now": "ယခု အဆင့်မြှင့်ပါ",
        "partners": "မိတ်ဖက် အမှတ်တံဆိပ်များ",
        "partners_desc": "စီးပွားရေးမိတ်ဖက်များ",
        "service_center": "ဝန်ဆောင်မှုစင်တာ",
        "service_desc": "အသေးစိတ်သိရှိလိုပါက ဝန်ဆောင်မှုစင်တာသို့ ဆက်သွယ်ပါ",
        "invite": "သူငယ်ချင်းကို ဖိတ်ခေါ်မည်",
        "comp_qual": "ကုမ္ပဏီ အရည်အချင်းစစ်ဆေးချက်",

        "balance": "လက်ကျန်ငွေ",
        "credit_score": "ခရက်ဒစ်",
        "recharge": "ငွေဖြည့်",
        "withdraw": "ငွေထုတ်",
        "news": "သတင်း",
        "menu_invite": "သူငယ်ချင်းကို ဖိတ်ခေါ်မည်",
        "menu_order_record": "အော်ဒါမှတ်တမ်း",
        "menu_acc_details": "အကောင့်အသေးစိတ်",
        "menu_fund_pwd": "ရန်ပုံငွေစကားဝှက်",
        "menu_bank_card": "ဘဏ်ကဒ်",
        "menu_logout": "အကောင့်မှထွက်မည်",

        "lang_select": "ဘာသာစကားရွေးပါ",
        "confirm": "အတည်ပြု",
        "cancel": "မလုပ်တော့ပါ",

        // --- New: Alert & Bank Info ---
        "alert_account_blocked": "သင့်အကောင့်ကို ပိတ်ထားသည်။ ကျေးဇူးပြု၍ Admin ကို ဆက်သွယ်ပါ။",
        
        "bank_title": "ဘဏ်အချက်အလက်",
        "bank_grp_main": "အဓိကအချက်အလက်",
        "bank_grp_detail": "အသေးစိတ်",
        "bank_grp_wallet": "Digital / Wallet",
        
        "bank_lbl_holder": "အကောင့်ပိုင်ရှင်",
        "bank_ph_holder": "အမည်အပြည့်အစုံ",
        "bank_lbl_name": "ဘဏ်အမည်",
        "bank_ph_name": "ဘဏ်အမည်",
        "bank_lbl_acc": "အကောင့်နံပါတ်",
        "bank_ph_acc": "အကောင့်နံပါတ်",
        
        "bank_lbl_code": "ဘဏ်ကုဒ်",
        "bank_ph_code": "Bank Code",
        "bank_lbl_branch": "ဘဏ်ခွဲကုဒ်",
        "bank_ph_branch": "Branch Code",
        "bank_lbl_phone": "မှတ်ပုံတင်ဖုန်းနံပါတ်",
        "bank_ph_phone": "ဖုန်းနံပါတ်",
        "bank_lbl_addr": "မှတ်ပုံတင်လိပ်စာ",
        "bank_ph_addr": "လိပ်စာ / ဘဏ်ခွဲ",
        "bank_lbl_ifsc": "IFSC / CPF",
        "bank_ph_ifsc": "IFSC/CPF Code",
        
        "bank_lbl_digital": "Digital Account",
        "bank_ph_digital": "Digital Account ID",
        "bank_lbl_w_no": "Wallet နံပါတ်",
        "bank_ph_w_no": "Wallet Number",
        "bank_lbl_w_acc": "Wallet အမည်",
        "bank_ph_w_acc": "Wallet Account Name",
        
        "btn_save_data": "သိမ်းဆည်းမည်",
        "btn_cancel": "မလုပ်တော့ပါ",
        "modal_confirm_save": "သိမ်းဆည်းရန် အတည်ပြုပါ?",
        "modal_confirm_msg": "အကောင့်အချက်အလက်များကို ပြုပြင်လိုပါသလား?",
        "alert_save_success": "ဒေတာသိမ်းဆည်းမှု အောင်မြင်သည်"
    },

    // ============================================================
    // 🇨🇳 Chinese
    // ============================================================
    "zh": {
        "lang_name": "中文",
        "title_login": "登录 - Consumer",
        "title_home": "首页 - Consumer",
        "title_order": "订单记录",
        "title_task": "任务大厅",
        "title_service": "服务中心",
        "title_profile": "个人中心",
        "tab_all": "全部",
    "tab_pending": "待处理",
    "tab_completed": "已完成",
    "tab_frozen": "冻结",
    "txt_comm": "佣金",
    "btn_submit_order": "提交订单",
    "txt_no_data": "暂无数据",
    "txt_order_id": "订单号",
    "txt_order_time": "时间",

    "news_header": "新闻",
    "news_p1": "值此 CONSUMER PARTNER 成立 24 周年之际，为了感谢新老用户的大力支持，特推出以下活动。",
    "news_p2": "活动详情 :",
    "news_topup": "充值",
    "news_bonus": "送彩金",
    "news_p3": "更多奖励请提前联系客服咨询！",
    "news_footer": "CONSUMER PARTNER 团队祝大家生活愉快！",
    "news_loading_done": "加载完成",

    // --- Pending Order Warning ---
        "warn_pending_title": "有未完成订单！",
        "warn_pending_msg": "您有尚未完成的订单！<br>请先完成订单处理。",
        "btn_go_order": "去处理",

        "login_header": "登录",
        "mobile_label": "手机号码*",
        "password_label": "登录密码*",
        "ph_mobile": "请输入手机号码",
        "ph_pass": "请输入密码",
        "login_btn": "登录",
        "register_btn": "去注册",

        "reg_header": "注册账户",
    "reg_mobile": "手机号码*",
    "reg_ph_mobile": "请输入手机号码",
    "reg_pass": "登录密码*",
    "reg_ph_pass": "请输入密码",
    "reg_confirm_pass": "确认密码*",
    "reg_ph_confirm_pass": "请再次输入密码",
    "reg_invite": "邀请码*",
    "reg_ph_invite": "请输入邀请码",
    "reg_agree": "我同意服务条款",
    "reg_btn_submit": "立即注册",
    "alert_reg_success": "注册成功",
    "alert_reg_fail": "注册失败",
    "alert_pass_mismatch": "两次输入的密码不一致",
    "alert_invite_invalid": "邀请码无效（系统中未找到）",
    "alert_user_exists": "该手机号已被注册",
    "alert_term_agree": "请同意服务条款",

        "work_checking": "正在检查状态...",
    "work_loading_products": "正在加载商品...",
    "work_matching": "正在匹配订单...",
    "modal_matched_title": "匹配成功！",
    "modal_total_order": "订单总额",
    "modal_commission": "佣金",
    "modal_return": "预计返还",
    "modal_rating": "评分",
    "modal_review_label": "评价",
    "btn_submit_now": "立即提交",
    "alert_submit_success": "提交成功！",
    "alert_submit_msg": "佣金已到账",

    // ... (ภาษาจีน "zh")
    "modal_verify_title": "验证身份",
    "modal_verify_desc": "请输入密码以继续",
    "ph_verify_pwd": "您的密码",
    "btn_confirm": "确认",
    "alert_wrong_pwd_title": "密码错误",
    "alert_wrong_pwd_msg": "密码不正确",
    "modal_amount_title": "输入金额",
    "txt_min_amount": "最低:",
    "txt_pay_negative": "支付负余额",
    "btn_deposit_submit": "提交充值",
    "alert_invalid_amount": "请输入有效金额",
    "alert_amount_title": "金额无效",
    "alert_need_min": "最低要求",
    "alert_sending": "正在发送...",
    "modal_dep_success_title": "充值提交成功",
    "modal_dep_success_msg": "请求已发送<br>请联系管理员核实",
    "btn_contact_admin": "联系管理员",
    "btn_close_window": "关闭窗口",

    // --- Withdrawal ---
    "modal_wd_title_1": "收款账户信息",
    "lbl_bank": "银行名称",
    "ph_bank": "银行名称",
    "lbl_acc_name": "账户名称",
    "ph_acc_name": "真实姓名",
    "lbl_acc_no": "银行账号",
    "ph_acc_no": "无需横杠",
    "btn_next": "下一步",
    
    "modal_wd_title_2": "提现详情",
    "lbl_net_balance": "净余额 (Net):",
    "lbl_frozen": "冻结金额 (Frozen):",
    "lbl_actual_withdraw": "可提现金额:",
    "lbl_fee": "手续费",
    "lbl_receive_amount": "实际到账:",
    "ph_wd_pwd": "确认密码",
    "btn_confirm_wd": "确认提现",
    
    "alert_wd_success_title": "已处理",
    "alert_wd_success_msg": "提现申请已发送<br>请联系管理员审核",
    
    "alert_incomplete_info": "信息不完整",
    "alert_fill_bank": "请填写完整的银行信息",
    "alert_checking_limit": "正在检查额度...",
    "alert_quota_exceeded": "配额已满",
    "alert_quota_msg": "您的提现次数已达上限",
    "alert_wd_min": "金额过低",
    "alert_wd_min_msg": "最低提现金额:",
    "alert_wd_bal_low": "余额不足",
    "alert_wd_frozen_msg": "可用余额不足 (可能被冻结)",

    // --- Service Page ---
    "service_title": "服务中心",
    "service_banner_title": "需要帮助吗？",
    "service_banner_desc": "24小时随时联系客服",
    "service_line_main": "Line Official (主要的)",
    "service_line_backup": "Line Official (备份)",
    "service_line_desc": "通过 Line 联系",
    "service_faq_title": "常见问题 (FAQ)",
    "faq_q1": "提现需要多长时间？",
    "faq_a1": "通常在 15-30 分钟内处理",
    "faq_q2": "充值未到账？",
    "faq_a2": "请通过 Line 或 Telegram 将凭证发送给管理员",
    "faq_q3": "工作时间？",
    "faq_a3": "我们提供 24 小时服务",
    
    // --- Contact Modal ---
    "modal_contact_title": "联系客服",
    "modal_line_id": "Line ID:",
    "btn_copy": "复制",
    "alert_copied": "已复制到剪贴板",

    // --- Review Options ---
    "rev_opt_1": "商品质量极佳，与描述完全一致。",
    "rev_opt_2": "非常满意，会再次购买。",
    "rev_opt_3": "价格合理，非常喜欢。",
    "rev_opt_4": "这次购物体验非常满意。",
    "rev_opt_5": "发货速度快，服务态度好。",

        "work_title": "任务大厅",
    "work_commission_rate": "佣金比例:",
    "work_today_comm": "今日佣金",
    "work_frozen": "冻结金额",
    "work_completed": "已完成订单",
    "work_balance": "账户余额",
    "work_start_btn": "开始抢单",

  "work_desc_title": "说明",
    "work_desc_1": "1. 系统基于LBS技术，通过云端自动匹配商品。",
    "work_desc_2": "2. 任务无法取消。您必须先完成未完成的任务，才能领取新任务。",
    "work_warn_title": "警告",
    "work_warn_text": "平台匹配订单后，数据发送至卖家后台。如30分钟内未提交，系统将冻结订单金额以规避监管。系统将对账户评分，影响下次匹配时间和信誉！请立即点击停止抢单，以免超时被冻结。",
        "alert_success": "成功",
        "alert_welcome": "欢迎",
        "alert_error": "错误",
        "alert_login_fail": "手机号码或密码错误",
        "alert_fill_info": "请填写完整信息",
        "alert_connecting": "正在连接... 请稍候",
        "invite_code_title": "邀请码",
        "invite_code_msg": "您的邀请码是：",
        "confirm_logout": "确定要退出登录吗？",

        // --- Notifications ---
        "notif_header": "通知",
        "notif_close": "关闭",
        "notif_empty": "暂无通知",
        "n_wd_wait": "提现申请",
        "n_wd_ok": "提现成功",
        "n_wd_fail": "提现失败",
        "n_rc_wait": "充值申请",
        "n_rc_ok": "充值成功",
        "n_rc_fail": "充值失败",
        "n_msg_wait": "等待审核",
        "n_msg_ok_wd": "已批准，款项已汇入",
        "n_msg_ok_rc": "已入账",
        "n_msg_fail": "已拒绝",
        "n_amt": "金额",

        "nav_home": "首页",
        "nav_order": "订单",
        "nav_task": "任务",
        "nav_service": "客服",
        "nav_my": "我的",

        "daily_tasks": "日常任务",
        "urgent_tasks": "紧急任务佣金更高",
        "loading_products": "正在加载商品...",
        "no_products": "暂无商品",
        "start_work": "开始抢单",
        "mem_benefits": "会员权益",
        "mem_desc": "会员等级越高，任务越多<br>享受更多收益。",
        "upgrade_now": "立即升级",
        "partners": "合作品牌",
        "partners_desc": "品牌合作伙伴",
        "service_center": "服务中心",
        "service_desc": "如有更多疑问，请联系我们的客户服务中心",
        "invite": "邀请好友",
        "comp_qual": "公司资质",

        "balance": "账户余额",
        "credit_score": "信用分",
        "recharge": "充值",
        "withdraw": "提现",
        "news": "新闻",
        "menu_invite": "邀请好友",
        "menu_order_record": "订单记录",
        "menu_acc_details": "账户明细",
        "menu_fund_pwd": "资金密码",
        "menu_bank_card": "银行卡",
        "menu_logout": "退出登录",

        "lang_select": "选择语言",
        "confirm": "确认",
        "cancel": "取消",

        // --- New: Alert & Bank Info ---
        "alert_account_blocked": "您的账户已被冻结。请联系管理员。",
        
        "bank_title": "银行信息",
        "bank_grp_main": "主要信息",
        "bank_grp_detail": "详细信息",
        "bank_grp_wallet": "数字账户 / 钱包",
        
        "bank_lbl_holder": "开户人姓名",
        "bank_ph_holder": "真实姓名",
        "bank_lbl_name": "银行名称",
        "bank_ph_name": "银行名称",
        "bank_lbl_acc": "银行账号",
        "bank_ph_acc": "银行账号",
        
        "bank_lbl_code": "银行代码",
        "bank_ph_code": "Bank Code",
        "bank_lbl_branch": "支行代码",
        "bank_ph_branch": "Branch Code",
        "bank_lbl_phone": "预留手机号",
        "bank_ph_phone": "手机号码",
        "bank_lbl_addr": "开户地址",
        "bank_ph_addr": "地址 / 支行",
        "bank_lbl_ifsc": "IFSC / CPF",
        "bank_ph_ifsc": "IFSC/CPF 代码",
        
        "bank_lbl_digital": "数字账户",
        "bank_ph_digital": "Digital Account ID",
        "bank_lbl_w_no": "钱包号码",
        "bank_ph_w_no": "Wallet Number",
        "bank_lbl_w_acc": "钱包账户名",
        "bank_ph_w_acc": "Wallet Account Name",
        
        "btn_save_data": "保存数据",
        "btn_cancel": "取消",
        "modal_confirm_save": "确认保存？",
        "modal_confirm_msg": "您确定要更新账户信息吗？",
        "alert_save_success": "数据保存成功"
    },

    // ============================================================
    // 🇯🇵 Japanese
    // ============================================================
    "jp": {
        "lang_name": "日本語",
        "title_login": "ログイン - Consumer",
        "title_home": "ホーム - Consumer",
        "title_order": "注文履歴",
        "title_task": "タスクホール",
        "title_service": "サービスセンター",
        "title_profile": "マイプロフィール",
        "tab_all": "すべて",
    "tab_pending": "保留中",
    "tab_completed": "完了",
    "tab_frozen": "凍結",
    "txt_comm": "手数料",
    "btn_submit_order": "注文を送信",
    "txt_no_data": "データなし",
    "txt_order_id": "注文ID",
    "txt_order_time": "時間",

        "login_header": "ログイン",
        "mobile_label": "携帯電話番号*",
        "password_label": "パスワード*",
        "ph_mobile": "電話番号を入力してください",
        "ph_pass": "パスワードを入力してください",
        "login_btn": "ログイン",
        "register_btn": "登録へ",

        // --- Pending Order Warning ---
        "warn_pending_title": "未完了の注文！",
        "warn_pending_msg": "未完了の注文があります！<br>先に注文を完了してください。",
        "btn_go_order": "注文を確認",

        "reg_header": "アカウント登録",
    "reg_mobile": "携帯電話番号*",
    "reg_ph_mobile": "電話番号を入力してください",
    "reg_pass": "ログインパスワード*",
    "reg_ph_pass": "パスワードを入力してください",
    "reg_confirm_pass": "パスワード（確認用）*",
    "reg_ph_confirm_pass": "パスワードを再入力してください",
    "reg_invite": "招待コード*",
    "reg_ph_invite": "招待コードを入力してください",
    "reg_agree": "利用規約に同意します",
    "reg_btn_submit": "登録する",
    "alert_reg_success": "登録が完了しました",
    "alert_reg_fail": "登録に失敗しました",
    "alert_pass_mismatch": "パスワードが一致しません",
    "alert_invite_invalid": "招待コードが無効です（システムに見つかりません）",
    "alert_user_exists": "この電話番号は既に使用されています",
    "alert_term_agree": "利用規約に同意してください",

        "news_header": "ニュース",
    "news_p1": "CONSUMER PARTNERの24周年を記念して、皆様の変わらぬご愛顧に感謝し、以下のキャンペーンを実施いたします。",
    "news_p2": "キャンペーン内容 :",
    "news_topup": "チャージ",
    "news_bonus": "ボーナス",
    "news_p3": "さらなる報酬については、カスタマーサービスまでお問い合わせください！",
    "news_footer": "CONSUMER PARTNER チーム一同、皆様の幸せをお祈り申し上げます！",
    "news_loading_done": "読み込み完了",

        "alert_success": "成功",
        "alert_welcome": "ようこそ",
        "alert_error": "エラー",
        "alert_login_fail": "携帯電話番号またはパスワードが間違っています",
        "alert_fill_info": "すべての情報を入力してください",
        "alert_connecting": "接続中... お待ちください",
        "invite_code_title": "招待コード",
        "invite_code_msg": "あなたの招待コードは：",
        "confirm_logout": "ログアウトしますか？",

        // ... (ภาษาญี่ปุ่น "jp")
    "modal_verify_title": "本人確認",
    "modal_verify_desc": "続行するにはパスワードを入力してください",
    "ph_verify_pwd": "パスワード",
    "btn_confirm": "確認",
    "alert_wrong_pwd_title": "パスワードエラー",
    "alert_wrong_pwd_msg": "パスワードが間違っています",
    "modal_amount_title": "金額を入力",
    "txt_min_amount": "最低:",
    "txt_pay_negative": "マイナス残高の支払い",
    "btn_deposit_submit": "チャージ申請",
    "alert_invalid_amount": "有効な金額を入力してください",
    "alert_amount_title": "金額が無効です",
    "alert_need_min": "最低必要額",
    "alert_sending": "送信中...",
    "modal_dep_success_title": "チャージ申請成功",
    "modal_dep_success_msg": "リクエストが送信されました<br>管理者に連絡して確認してください",
    "btn_contact_admin": "管理者に連絡",
    "btn_close_window": "閉じる",

        // --- Service Page ---
    "service_title": "サービスセンター",
    "service_banner_title": "お困りですか？",
    "service_banner_desc": "24時間いつでもカスタマーサポートにご連絡ください",
    "service_line_main": "Line Official (主要)",
    "service_line_backup": "Line Official (バックアップ)",
    "service_line_desc": "Lineで連絡する",
    "service_faq_title": "よくある質問 (FAQ)",
    "faq_q1": "出金にはどのくらい時間がかかりますか？",
    "faq_a1": "通常15〜30分以内に処理されます",
    "faq_q2": "チャージが反映されませんか？",
    "faq_a2": "LineまたはTelegramで管理者に明細書を送信してください",
    "faq_q3": "営業時間？",
    "faq_a3": "24時間対応しています",
    
    // --- Contact Modal ---
    "modal_contact_title": "サポートに連絡",
    "modal_line_id": "Line ID:",
    "btn_copy": "コピー",
    "alert_copied": "クリップボードにコピーしました",

        "work_checking": "ステータスを確認中...",
    "work_loading_products": "商品を読み込み中...",
    "work_matching": "注文をマッチング中...",
    "modal_matched_title": "マッチング成功！",
    "modal_total_order": "注文合計",
    "modal_commission": "手数料",
    "modal_return": "返還額",
    "modal_rating": "評価",
    "modal_review_label": "レビュー",
    "btn_submit_now": "今すぐ送信",
    "alert_submit_success": "送信成功！",
    "alert_submit_msg": "報酬が入金されました",

    // --- Withdrawal ---
    "modal_wd_title_1": "受取口座情報",
    "lbl_bank": "銀行名",
    "ph_bank": "銀行名",
    "lbl_acc_name": "口座名義",
    "ph_acc_name": "氏名",
    "lbl_acc_no": "口座番号",
    "ph_acc_no": "ハイフンなし",
    "btn_next": "次へ",
    
    "modal_wd_title_2": "出金詳細",
    "lbl_net_balance": "純残高 (Net):",
    "lbl_frozen": "凍結中 (Frozen):",
    "lbl_actual_withdraw": "出金可能額:",
    "lbl_fee": "手数料",
    "lbl_receive_amount": "受取予定額:",
    "ph_wd_pwd": "確認パスワード",
    "btn_confirm_wd": "出金を確定",
    
    "alert_wd_success_title": "処理完了",
    "alert_wd_success_msg": "出金申請が送信されました<br>管理者に連絡して承認を受けてください",
    
    "alert_incomplete_info": "情報が不完全です",
    "alert_fill_bank": "銀行情報をすべて入力してください",
    "alert_checking_limit": "限度額を確認中...",
    "alert_quota_exceeded": "上限到達",
    "alert_quota_msg": "出金回数の上限に達しました",
    "alert_wd_min": "金額が低すぎます",
    "alert_wd_min_msg": "最低出金金額:",
    "alert_wd_bal_low": "残高不足",
    "alert_wd_frozen_msg": "出金可能残高が不足しています (凍結中の可能性があります)",

    // --- Review Options ---
    "rev_opt_1": "品質が素晴らしく、説明通りです。",
    "rev_opt_2": "大変満足しており、また購入します。",
    "rev_opt_3": "手頃な価格で大変気に入りました。",
    "rev_opt_4": "非常に満足のいくショッピング体験でした。",
    "rev_opt_5": "配送が早く、サービスも良かったです。",

        "work_title": "タスクホール",
    "work_commission_rate": "手数料率:",
    "work_today_comm": "本日の手数料",
    "work_frozen": "凍結金額",
    "work_completed": "完了した注文",
    "work_balance": "口座残高",
    "work_start_btn": "注文取りを開始",
  "work_desc_title": "説明",
    "work_desc_1": "1. システムはLBS技術に基づき、クラウド経由で商品を自動マッチングします。",
    "work_desc_2": "2. タスクはキャンセルできません。新しいタスクを受ける前に、未完了のタスクを完了する必要があります。",
    "work_warn_title": "警告",
    "work_warn_text": "マッチング後、データは販売者に送信されます。30分以内に送信しない場合、規制遵守のため金額が凍結されます。システムはアカウントを評価し、次回マッチングや評判に影響します！タイムアウト凍結を避けるため、直ちに注文停止をクリックしてください。",
        // --- Notifications ---
        "notif_header": "通知",
        "notif_close": "閉じる",
        "notif_empty": "通知はありません",
        "n_wd_wait": "出金申請",
        "n_wd_ok": "出金成功",
        "n_wd_fail": "出金失敗",
        "n_rc_wait": "チャージ申請",
        "n_rc_ok": "チャージ成功",
        "n_rc_fail": "チャージ失敗",
        "n_msg_wait": "審査待ち",
        "n_msg_ok_wd": "承認済み、送金完了",
        "n_msg_ok_rc": "反映されました",
        "n_msg_fail": "拒否されました",
        "n_amt": "金額",

        "nav_home": "ホーム",
        "nav_order": "注文",
        "nav_task": "タスク",
        "nav_service": "サービス",
        "nav_my": "マイページ",

        "daily_tasks": "デイリータスク",
        "urgent_tasks": "緊急タスクは手数料が高くなります",
        "loading_products": "商品を読み込んでいます...",
        "no_products": "商品がありません",
        "start_work": "注文取りを開始",
        "mem_benefits": "会員特典",
        "mem_desc": "会員レベルが高いほど、より多くのタスクを引き受け<br>より多くの収益を得ることができます。",
        "upgrade_now": "今すぐアップグレード",
        "partners": "パートナーブランド",
        "partners_desc": "ブランドパートナー",
        "service_center": "サービスセンター",
        "service_desc": "ご不明な点がございましたら、カスタマーサービスセンターまでお問い合わせください",
        "invite": "友達を招待",
        "comp_qual": "会社概要",

        "balance": "口座残高",
        "credit_score": "クレジットスコア",
        "recharge": "チャージ",
        "withdraw": "出金",
        "news": "ニュース",
        "menu_invite": "友達を招待",
        "menu_order_record": "注文履歴",
        "menu_acc_details": "アカウント詳細",
        "menu_fund_pwd": "資金パスワード",
        "menu_bank_card": "銀行カード",
        "menu_logout": "ログアウト",

        "lang_select": "言語を選択",
        "confirm": "確認",
        "cancel": "キャンセル",

        // --- New: Alert & Bank Info ---
        "alert_account_blocked": "アカウントが停止されています。管理者に連絡してください。",
        
        "bank_title": "銀行情報",
        "bank_grp_main": "主要情報",
        "bank_grp_detail": "詳細",
        "bank_grp_wallet": "デジタル / ウォレット",
        
        "bank_lbl_holder": "口座名義人",
        "bank_ph_holder": "氏名",
        "bank_lbl_name": "銀行名",
        "bank_ph_name": "銀行名",
        "bank_lbl_acc": "口座番号",
        "bank_ph_acc": "口座番号",
        
        "bank_lbl_code": "銀行コード",
        "bank_ph_code": "Bank Code",
        "bank_lbl_branch": "支店コード",
        "bank_ph_branch": "Branch Code",
        "bank_lbl_phone": "登録電話番号",
        "bank_ph_phone": "電話番号",
        "bank_lbl_addr": "登録住所",
        "bank_ph_addr": "住所 / 支店",
        "bank_lbl_ifsc": "IFSC / CPF",
        "bank_ph_ifsc": "IFSC/CPF コード",
        
        "bank_lbl_digital": "デジタルアカウント",
        "bank_ph_digital": "Digital Account ID",
        "bank_lbl_w_no": "ウォレット番号",
        "bank_ph_w_no": "Wallet Number",
        "bank_lbl_w_acc": "ウォレット名義",
        "bank_ph_w_acc": "Wallet Account Name",
        
        "btn_save_data": "保存",
        "btn_cancel": "キャンセル",
        "modal_confirm_save": "保存しますか？",
        "modal_confirm_msg": "アカウント情報を更新しますか？",
        "alert_save_success": "データが正常に保存されました"
    },

    // ============================================================
    // 🇻🇳 Vietnamese
    // ============================================================
    "vn": {
        "lang_name": "Tiếng Việt",
        "title_login": "Đăng nhập - Consumer",
        "title_home": "Trang chủ - Consumer",
        "title_order": "Lịch sử đơn hàng",
        "title_task": "Sảnh nhiệm vụ",
        "title_service": "Trung tâm dịch vụ",
        "title_profile": "Hồ sơ của tôi",

        "news_header": "Tin tức",
    "news_p1": "Nhân dịp kỷ niệm 24 năm thành lập CONSUMER PARTNER, chúng tôi ra mắt các hoạt động sau để tri ân khách hàng đã ủng hộ.",
    "news_p2": "Chi tiết hoạt động :",
    "news_topup": "Nạp",
    "news_bonus": "Tặng thưởng",
    "news_p3": "Để biết thêm phần thưởng, vui lòng liên hệ CSKH để được tư vấn!",
    "news_footer": "Đội ngũ CONSUMER PARTNER chúc mọi người hạnh phúc!",
    "news_loading_done": "Đã tải xong",

        "login_header": "Đăng nhập",
        "mobile_label": "Số điện thoại*",
        "password_label": "Mật khẩu*",
        "ph_mobile": "Nhập số điện thoại",
        "ph_pass": "Nhập mật khẩu",
        "login_btn": "Đăng nhập",
        "register_btn": "Đăng ký",

        // --- Pending Order Warning ---
        "warn_pending_title": "Đơn hàng treo!",
        "warn_pending_msg": "Bạn có đơn hàng chưa hoàn tất!<br>Vui lòng xử lý trước.",
        "btn_go_order": "Đi xử lý",

        "reg_header": "Đăng ký tài khoản",
    "reg_mobile": "Số điện thoại*",
    "reg_ph_mobile": "Vui lòng nhập số điện thoại",
    "reg_pass": "Mật khẩu đăng nhập*",
    "reg_ph_pass": "Vui lòng nhập mật khẩu",
    "reg_confirm_pass": "Xác nhận mật khẩu*",
    "reg_ph_confirm_pass": "Vui lòng xác nhận mật khẩu",
    "reg_invite": "Mã mời*",
    "reg_ph_invite": "Vui lòng nhập mã mời",
    "reg_agree": "Tôi đồng ý với Điều khoản dịch vụ",
    "reg_btn_submit": "Đăng ký ngay",
    "alert_reg_success": "Đăng ký thành công",
    "alert_reg_fail": "Đăng ký thất bại",
    "alert_pass_mismatch": "Mật khẩu không khớp",
    "alert_invite_invalid": "Mã mời không hợp lệ (không tìm thấy trong hệ thống)",
    "alert_user_exists": "Số điện thoại này đã được sử dụng",
    "alert_term_agree": "Vui lòng đồng ý với các điều khoản dịch vụ",

        // ... (ภาษาเวียดนาม "vn")
    "modal_verify_title": "Xác minh danh tính",
    "modal_verify_desc": "Vui lòng nhập mật khẩu để tiếp tục",
    "ph_verify_pwd": "Mật khẩu của bạn",
    "btn_confirm": "Xác nhận",
    "alert_wrong_pwd_title": "Sai mật khẩu",
    "alert_wrong_pwd_msg": "Mật khẩu không chính xác",
    "modal_amount_title": "Nhập số tiền",
    "txt_min_amount": "Tối thiểu:",
    "txt_pay_negative": "Thanh toán số dư âm",
    "btn_deposit_submit": "Gửi nạp tiền",
    "alert_invalid_amount": "Vui lòng nhập số tiền hợp lệ",
    "alert_amount_title": "Số tiền không hợp lệ",
    "alert_need_min": "Yêu cầu tối thiểu",
    "alert_sending": "Đang gửi...",
    "modal_dep_success_title": "Gửi yêu cầu thành công",
    "modal_dep_success_msg": "Yêu cầu của bạn đã được gửi<br>Vui lòng liên hệ Admin để xác nhận",
    "btn_contact_admin": "Liên hệ Admin",
    "btn_close_window": "Đóng cửa sổ",

        "work_checking": "Đang kiểm tra trạng thái...",
    "work_loading_products": "Đang tải sản phẩm...",
    "work_matching": "Đang khớp đơn hàng...",
    "modal_matched_title": "Khớp đơn thành công!",
    "modal_total_order": "Tổng đơn hàng",
    "modal_commission": "Hoa hồng",
    "modal_return": "Số tiền hoàn lại",
    "modal_rating": "Đánh giá",
    "modal_review_label": "Nhận xét",
    "btn_submit_now": "Gửi đơn ngay",
    "alert_submit_success": "Gửi thành công!",
    "alert_submit_msg": "Hoa hồng đã được cộng vào tài khoản",

    // --- Withdrawal ---
    "modal_wd_title_1": "Thông tin tài khoản nhận",
    "lbl_bank": "Ngân hàng",
    "ph_bank": "Ngân hàng",
    "lbl_acc_name": "Tên tài khoản",
    "ph_acc_name": "Họ và tên",
    "lbl_acc_no": "Số tài khoản",
    "ph_acc_no": "Không nhập dấu gạch ngang",
    "btn_next": "Tiếp theo",
    
    "modal_wd_title_2": "Chi tiết rút tiền",
    "lbl_net_balance": "Số dư thực (Net):",
    "lbl_frozen": "Đóng băng (Frozen):",
    "lbl_actual_withdraw": "Có thể rút:",
    "lbl_fee": "Phí",
    "lbl_receive_amount": "Thực nhận:",
    "ph_wd_pwd": "Mật khẩu xác nhận",
    "btn_confirm_wd": "Xác nhận rút tiền",
    
    "alert_wd_success_title": "Đã xử lý",
    "alert_wd_success_msg": "Yêu cầu rút tiền đã được gửi<br>Vui lòng liên hệ Admin để duyệt",
    
    "alert_incomplete_info": "Thông tin chưa đủ",
    "alert_fill_bank": "Vui lòng điền đầy đủ thông tin ngân hàng",
    "alert_checking_limit": "Đang kiểm tra hạn mức...",
    "alert_quota_exceeded": "Hết hạn mức",
    "alert_quota_msg": "Bạn đã đạt giới hạn số lần rút tiền",
    "alert_wd_min": "Số tiền quá thấp",
    "alert_wd_min_msg": "Số tiền rút tối thiểu:",
    "alert_wd_bal_low": "Số dư không đủ",
    "alert_wd_frozen_msg": "Số dư khả dụng không đủ (Có thể bị đóng băng)",

    // --- Service Page ---
    "service_title": "Trung tâm dịch vụ",
    "service_banner_title": "Cần giúp đỡ?",
    "service_banner_desc": "Liên hệ hỗ trợ khách hàng 24/7",
    "service_line_main": "Line Official (chủ yếu)",
    "service_line_backup": "Line Official (hỗ trợ)",
    "service_line_desc": "Liên hệ qua Line",
    "service_faq_title": "Câu hỏi thường gặp (FAQ)",
    "faq_q1": "Rút tiền mất bao lâu?",
    "faq_a1": "Thường được xử lý trong vòng 15-30 phút",
    "faq_q2": "Chưa nhận được tiền nạp?",
    "faq_a2": "Vui lòng gửi biên lai cho Admin qua Line hoặc Telegram",
    "faq_q3": "Giờ làm việc?",
    "faq_a3": "Chúng tôi phục vụ 24 giờ",
    
    // --- Contact Modal ---
    "modal_contact_title": "Liên hệ hỗ trợ",
    "modal_line_id": "Line ID:",
    "btn_copy": "Sao chép",
    "alert_copied": "Đã sao chép vào bộ nhớ tạm",

    // --- Review Options ---
    "rev_opt_1": "Chất lượng sản phẩm tuyệt vời, đúng như mô tả.",
    "rev_opt_2": "Rất hài lòng và sẽ mua lại.",
    "rev_opt_3": "Rất hài lòng với mức giá hợp lý.",
    "rev_opt_4": "Trải nghiệm mua sắm rất hài lòng.",
    "rev_opt_5": "Giao hàng nhanh và dịch vụ tốt.",

        "tab_all": "Tất cả",
    "tab_pending": "Chờ xử lý",
    "tab_completed": "Hoàn thành",
    "tab_frozen": "Đóng băng",
    "txt_comm": "Hoa hồng",
    "btn_submit_order": "Gửi đơn",
    "txt_no_data": "Không có dữ liệu",
    "txt_order_id": "Mã đơn",
    "txt_order_time": "Thời gian",

    "work_title": "Sảnh nhiệm vụ",
    "work_commission_rate": "Tỷ lệ hoa hồng:",
    "work_today_comm": "Hoa hồng hôm nay",
    "work_frozen": "Số tiền đóng băng",
    "work_completed": "Đơn hàng hoàn thành",
    "work_balance": "Số dư tài khoản",
    "work_start_btn": "Bắt đầu nhận đơn",

 "work_desc_title": "Mô tả",
    "work_desc_1": "1. Hệ thống dựa trên công nghệ LBS và tự động khớp sản phẩm qua đám mây.",
    "work_desc_2": "2. Bạn không thể hủy nhiệm vụ. Phải hoàn thành nhiệm vụ chưa xong trước khi nhận mới.",
    "work_warn_title": "Cảnh báo",
    "work_warn_text": "Khi khớp đơn, dữ liệu được gửi đến người bán. Nếu không gửi trong 30 phút, số tiền sẽ bị đóng băng để tuân thủ quy định. Hệ thống sẽ chấm điểm tài khoản, ảnh hưởng đến lần khớp sau! Vui lòng bấm dừng đặt hàng ngay để tránh bị đóng băng do quá giờ.",
        "alert_success": "Thành công",
        "alert_welcome": "Chào mừng",
        "alert_error": "Lỗi",
        "alert_login_fail": "Số điện thoại hoặc mật khẩu không chính xác",
        "alert_fill_info": "Vui lòng điền đầy đủ thông tin",
        "alert_connecting": "Đang kết nối... Vui lòng đợi",
        "invite_code_title": "Mã mời",
        "invite_code_msg": "Mã mời của bạn là:",
        "confirm_logout": "Bạn có chắc chắn muốn đăng xuất?",

        // --- Notifications ---
        "notif_header": "Thông báo",
        "notif_close": "Đóng",
        "notif_empty": "Không có thông báo",
        "n_wd_wait": "Yêu cầu rút tiền",
        "n_wd_ok": "Rút tiền thành công",
        "n_wd_fail": "Rút tiền thất bại",
        "n_rc_wait": "Yêu cầu nạp tiền",
        "n_rc_ok": "Nạp tiền thành công",
        "n_rc_fail": "Nạp tiền thất bại",
        "n_msg_wait": "Đang chờ duyệt",
        "n_msg_ok_wd": "Đã duyệt, tiền đã chuyển",
        "n_msg_ok_rc": "Đã cộng vào ví",
        "n_msg_fail": "Bị từ chối",
        "n_amt": "Số tiền",

        "nav_home": "Trang chủ",
        "nav_order": "Đơn hàng",
        "nav_task": "Nhiệm vụ",
        "nav_service": "Dịch vụ",
        "nav_my": "Của tôi",

        "daily_tasks": "Nhiệm vụ hàng ngày",
        "urgent_tasks": "Hoa hồng cao hơn cho nhiệm vụ khẩn cấp",
        "loading_products": "Đang tải sản phẩm...",
        "no_products": "Không có sản phẩm",
        "start_work": "Bắt đầu nhận đơn",
        "mem_benefits": "Quyền lợi thành viên",
        "mem_desc": "Cấp độ thành viên càng cao, nhận càng nhiều nhiệm vụ<br>để tận hưởng thu nhập nhiều hơn.",
        "upgrade_now": "Nâng cấp ngay",
        "partners": "Thương hiệu đối tác",
        "partners_desc": "Đối tác thương hiệu",
        "service_center": "Trung tâm dịch vụ",
        "service_desc": "Để biết thêm chi tiết, vui lòng liên hệ Trung tâm Dịch vụ Khách hàng",
        "invite": "Mời bạn bè",
        "comp_qual": "Chứng nhận công ty",

        "balance": "Số dư",
        "credit_score": "Điểm tín dụng",
        "recharge": "Nạp tiền",
        "withdraw": "Rút tiền",
        "news": "Tin tức",
        "menu_invite": "Mời bạn bè",
        "menu_order_record": "Lịch sử đơn hàng",
        "menu_acc_details": "Chi tiết tài khoản",
        "menu_fund_pwd": "Mật khẩu quỹ",
        "menu_bank_card": "Thẻ ngân hàng",
        "menu_logout": "Đăng xuất",

        "lang_select": "Chọn ngôn ngữ",
        "confirm": "Xác nhận",
        "cancel": "Hủy bỏ",

        // --- New: Alert & Bank Info ---
        "alert_account_blocked": "Tài khoản của bạn đã bị đình chỉ. Vui lòng liên hệ Admin.",
        
        "bank_title": "Thông tin ngân hàng",
        "bank_grp_main": "Thông tin chính",
        "bank_grp_detail": "Chi tiết",
        "bank_grp_wallet": "Kỹ thuật số / Ví",
        
        "bank_lbl_holder": "Chủ tài khoản",
        "bank_ph_holder": "Họ và tên",
        "bank_lbl_name": "Tên ngân hàng",
        "bank_ph_name": "Tên ngân hàng",
        "bank_lbl_acc": "Số tài khoản",
        "bank_ph_acc": "Số tài khoản",
        
        "bank_lbl_code": "Mã ngân hàng",
        "bank_ph_code": "Bank Code",
        "bank_lbl_branch": "Mã chi nhánh",
        "bank_ph_branch": "Branch Code",
        "bank_lbl_phone": "SĐT đăng ký",
        "bank_ph_phone": "Số điện thoại",
        "bank_lbl_addr": "Địa chỉ đăng ký",
        "bank_ph_addr": "Địa chỉ / Chi nhánh",
        "bank_lbl_ifsc": "IFSC / CPF",
        "bank_ph_ifsc": "Mã IFSC/CPF",
        
        "bank_lbl_digital": "Tài khoản số",
        "bank_ph_digital": "ID tài khoản số",
        "bank_lbl_w_no": "Số ví",
        "bank_ph_w_no": "Số ví",
        "bank_lbl_w_acc": "Tên ví",
        "bank_ph_w_acc": "Tên tài khoản ví",
        
        "btn_save_data": "Lưu dữ liệu",
        "btn_cancel": "Hủy bỏ",
        "modal_confirm_save": "Xác nhận lưu?",
        "modal_confirm_msg": "Bạn có muốn cập nhật thông tin tài khoản?",
        "alert_save_success": "Đã lưu dữ liệu thành công"
    }
};